# don't use Mega-Linter to test the reports Mega-Linter created
ADDITIONAL_EXCLUDED_DIRECTORIES: report

# when possible, apply fixes when PRs are created by adding a commit to the PR with the fixes
APPLY_FIXES: true
APPLY_FIXES_EVENT: pull_request
APPLY_FIXES_MODE: commit

# please don't spell check everything...
DISABLE_LINTERS: SPELL_MISSPELL, COPYPASTE_JSCPD, SPELL_CSPELL

# only scan new / updated files, not everything
VALIDATE_ALL_CODEBASE: false

# don't fail on finding (yet)
DISABLE_ERRORS: true
