---
version: '3.8'
services:
  postgres:
    container_name: postgres
    image: postgres:13
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - webnet

  redis:
    container_name: redis
    image: redis:5
    ports:
      - '6379:6379'
    networks:
      - webnet

  storage:
    container_name: minio
    image: minio/minio
    volumes:
      - ./storage/:/storage
    env_file:
      - .env
    command: server /storage
    ports:
      - '9000:9000'

  createbuckets:
    image: minio/mc
    depends_on:
      - storage
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://storage:9000 \
      \$MINIO_ACCESS_KEY \$MINIO_SECRET_KEY) do echo '...waiting...' \
      && sleep 1; done;
      /usr/bin/mc mb myminio/site-scanning-snapshot;
      /usr/bin/mc policy set download myminio/site-scanning-snapshot;
      exit 0;
      "

networks:
  webnet:
