# using this https://blog.logrocket.com/containerized-development-nestjs-docker/
# for inspiration
version: "3.8"
services:
    api:
        build: 
            context: "."
            dockerfile: "./apps/api/Dockerfile"
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports: 
            - "3000:3000"
        command: npm run start:dev api
        networks: 
            - webnet
        depends_on:
            - redis

    scanner:
        build:
            context: "."
            dockerfile: "./apps/scanner/Dockerfile"
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        command: npm run start:dev scanner
        security_opt:
            - "seccomp=./apps/scanner/chrome.json"
        networks:
            - webnet
        depends_on: 
            - redis

    redis:
        container_name: redis
        image: redis:5
        ports: 
            - "6379:6379"
        networks:
            - webnet

networks:
    webnet:

        
    