# using this https://blog.logrocket.com/containerized-development-nestjs-docker/
# for inspiration
version: "3.8"
services:
    postgres:
        container_name: postgres
        image: postgres:13
        env_file: 
            - .env
        ports:
            - "5432:5432"
        networks:
            - webnet

    redis:
        container_name: redis
        image: redis:5
        ports: 
            - "6379:6379"
        networks:
            - webnet

    s3:
        container_name: s3
        image: minio/minio
        command: server /data
        ports:
            - "9000:9000"
        env_file:
            - .env
        networks:
            - webnet

networks:
    webnet:

        
    