name: Write snapshot of current scans to S3
on:
  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: run create-snapshot cli job in chosen space
        uses: danielnaab/cg-cli-tools@no-exec
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space }}
          cf_command: 'run-task site-scanner-consumer -c "node dist/apps/cli/main.js create-snapshot" -k 4G -m 4G --name github-action-create-snapshot-${{ github.run_id }}'
