---
name: Deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: build
        run: npm run build:all

      - name: deploy api
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: prod
          push_arguments: "--vars-file vars.yml site-scanner-api"

      - name: deploy consumer
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: prod
          push_arguments: "--vars-file vars.yml site-scanner-consumer"


      - name: scale consumer
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: prod
          cf_command: 'scale site-scanner-consumer -i 4 -k 4G -m 2G -f'
          # scale to four instances with 2G memory each and force deploy
