---
name: Dev deployment

# yamllint disable-line rule:truthy
on:
  # Triggers workflow on pull request events for the main branch
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed
    # as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE,
      # so your job can access it
      - uses: actions/checkout@v2

      - name: install
        run: npm install

      - name: build
        run: npm run build:all

      - name: deploy api to dev
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: dev
          push_arguments: '--vars-file vars-dev.yml site-scanner-api'

      - name: deploy consumer to dev
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: dev
          push_arguments: '--vars-file vars-dev.yml site-scanner-consumer'

      - name: scale consumer
        uses: cloud-gov/cg-cli-tools@main@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: dev
          cf_command: 'scale site-scanner-consumer -i 1 -k 4G -m 512M -f'
          # scale to two instances with 4G scratch disk and 2G
          # memory each and force deploy
