name: Enqueue scans
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod

jobs:
  enqueue:
    runs-on: ubuntu-latest

    steps:
      - name: run enqueue-scans cli job in chosen space
        uses: danielnaab/cg-cli-tools@no-exec
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space || 'prod' }}
          cf_command: 'run-task site-scanner-consumer -c "node dist/apps/cli/main.js enqueue-scans" -k 2G -m 4G --name github-action-enqueue-scans-${{ github.run_id }}'
