---
name: Enqueue site

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod
      scan_url:
        description: url to be queued
        required: true
        type: string

jobs:
  enqueue:
    runs-on: ubuntu-latest

    steps:
      - name: run enqueue-site cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space || 'prod' }}
          cf_command: run-task site-scanner-consumer
            -c "node dist/apps/cli/main.js enqueue-site --url ${{ github.event.inputs.scan_url }}"
            -k 2G -m 2G
            --name github-action-enqueue-site-${{ github.run_id }}
