---
name: Fetch security data

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '30 22 * * *'

  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: run ingest cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: prod
          cf_command: |
            run-task site-scanner-consumer
            --command "node dist/apps/cli/main.js security-data"
            -k 2G -m 2G
            --name github-action-security-data-${{ github.run_id }}
