name: Ingest website list
on:
  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod
      federalSubdomainsUrl:
        description: CSV with domain list
        required: true
        default: 'https://raw.githubusercontent.com/GSA/federal-website-index/main/data/site-scanning-target-url-list.csv'

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: run ingest cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space }}
          command: 'cf run-task site-scanner-producer --command "node dist/apps/cli/main.js ingest" -k 2G -m 4G --name github-action-run-${{ github.run_id }}'
