---
name: Ingest website list
# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 21 * * 4'
  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod
      federalSubdomainsUrl:
        description: CSV with domain list (leave blank to use default)
        required: false

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: run ingest cli job in chosen space
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space }}
          cf_command: |
            run-task site-scanner-consumer
            --command "node dist/apps/cli/main.js ingest"
            -k 2G -m 4G
            --name github-action-ingest-${{ github.run_id }}
