---
name: Restart scan worker/consumer

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:
    inputs:
      cf_space:
        description: deployed cloud.gov space
        required: true
        default: prod

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: restart scan worker
        uses: cloud-gov/cg-cli-tools@main
        with:
          cf_api: https://api.fr.cloud.gov
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: gsatts-sitescan
          cf_space: ${{ github.event.inputs.cf_space || 'prod' }}
          cf_command: restart site-scanner-consumer
