---
name: woke

# yamllint disable-line rule:truthy
on:
  push:
  workflow_dispatch:
jobs:
  woke:
    name: woke
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: woke
        uses: get-woke/woke-action@v0
        with:
          fail-on-error: false
